const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { detectBuildSystem } = require('../src/main/flash/flasher');
const { KEIL_SUPPORTED } = require('../src/main/core/config');

function tempProject(name) {
  return fs.mkdtempSync(path.join(os.tmpdir(), `burningtool-${name}-`));
}

test('auto build system prefers Keil project over generic Makefile', () => {
  const dir = tempProject('keil-auto');
  fs.writeFileSync(path.join(dir, 'Project.uvprojx'), '<Project></Project>');
  fs.writeFileSync(path.join(dir, 'Makefile'), 'all:\n\t@echo generated by another tool\n');

  assert.equal(detectBuildSystem(dir, { buildSystem: 'auto' }), KEIL_SUPPORTED ? 'keil' : 'make');
});

test('auto build system uses Makefile when no Keil project exists', () => {
  const dir = tempProject('make-auto');
  fs.writeFileSync(path.join(dir, 'Makefile'), 'all:\n\t@echo make\n');

  assert.equal(detectBuildSystem(dir, { buildSystem: 'auto' }), 'make');
});
