/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    LogClearBtn: typeof import('./src/components/LogClearBtn.vue')['default']
    LogLineCount: typeof import('./src/components/LogLineCount.vue')['default']
    LogPanel: typeof import('./src/components/LogPanel.vue')['default']
    MqttMessages: typeof import('./src/components/MqttMessages.vue')['default']
    MqttMsgCount: typeof import('./src/components/MqttMsgCount.vue')['default']
    RamLogText: typeof import('./src/components/RamLogText.vue')['default']
    SerialByteStats: typeof import('./src/components/SerialByteStats.vue')['default']
    SerialTerminal: typeof import('./src/components/SerialTerminal.vue')['default']
  }
}
